apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: node-docker
  name: node-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-docker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: node-docker
    spec:
      containers:
        - env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          image: selenium/node-docker:4.1.3-20220405
          name: node-docker
          resources: {}
          volumeMounts:
            - mountPath: /opt/selenium/assets
              name: node-docker-claim0
            - mountPath: /opt/bin/config.toml
              name: node-docker-claim1
            - mountPath: /var/run/docker.sock
              name: node-docker-claim2
      restartPolicy: Always
      volumes:
        - name: node-docker-claim0
          persistentVolumeClaim:
            claimName: node-docker-claim0
        - name: node-docker-claim1
          persistentVolumeClaim:
            claimName: node-docker-claim1
        - name: node-docker-claim2
          persistentVolumeClaim:
            claimName: node-docker-claim2
status: {}
